apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: py9e51gsg-java-quarkus
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: py9e51gsg-java-quarkus 
  name: py9e51gsg-java-quarkus
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: py9e51gsg-java-quarkus 
